### ISSUE TITLE
Falta dependencia

### ISSUE THREAD

**Issue by enahum** [trollderius/i18n#1]
@trollderius aparentemente falta una dependencia y además cuando subo un archivo y le doy submit el programa se cae.

**Comment by oscar-gardiazabal** [comment]
perdón, se me olvidó actualizar las dependencias, un minuto

2016-03-14 16:24 GMT-03:00 enahum notifications@github.com:

**Comment by oscar-gardiazabal** [comment]
Lo siento, tengo un internet muy malo en donde estoy ahora. Ya está añadida
la dependencia que debería dejarte subir los archivos, al menos en mi pc
funciona.
disculpas
